inherit_from:
  - .rubocop_rspec.yml

##
# Standard based Rubocop config.
# - https://github.com/testdouble/standard
# - https://github.com/testdouble/standard#usage-via-rubocop
# - https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard
#
require:
  ##
  # Rubocop for RSpec files.
  # https://github.com/rubocop/rubocop-rspec#usage
  #
  - rubocop-rspec
  ##
  # NOTE: `rubocop-performance` is automatically bundled with Standard.
  #
  - rubocop-performance
  ##
  # NOTE: Custom Standard cop that should be loaded before `config/base.yml`.
  #
  - standard/cop/block_single_line_braces
  ##
  # A RuboCop Cop that detects the use of magic numbers within instance methods.
  # https://github.com/meetcleo/rubocop-magic_numbers
  #
  - rubocop-magic_numbers

inherit_gem:
  standard: config/base.yml

AllCops:
  ##
  # https://github.com/testdouble/standard#how-do-i-specify-a-ruby-version-what-is-supported
  #
  TargetRubyVersion: 2.7

  Exclude:
    ##
    # NOTE: Excludes vendor from linting. Needed by GitHub Actions.
    # - https://github.com/rubocop/rubocop/issues/9832
    # - https://github.com/rubocop/rubocop/issues/9832#issuecomment-873398952
    #
    - vendor/**/*

    ##
    # NOTE: Excludes dependencies from linting.
    #
    - lib/convenient_service/dependencies/**/*

MagicNumbers:
  Exclude:
    ##
    # NOTE: Excludes the following files/folders from linting magic numbers.
    # - https://github.com/meetcleo/rubocop-magic_numbers
    # - https://docs.rubocop.org/rubocop/configuration.html#includingexcluding-files
    #
    - Rakefile
    - benchmark/**/*
    - spec/**/*
    - test/**/*
