##
# NOTE: Tmuxinator config options.
# - https://github.com/tmuxinator/tmuxinator#create-a-project
#
name: convenient_service
root: .

on_project_start:
  - task editor:open
  - task docker:start
  - task github:open

windows:
  - main:
      layout: even-vertical
      root: .
      panes:
        - task docker:bash ENGINE=ruby VERSION=2.7
        - task docker:bash ENGINE=ruby VERSION=3.3
        - git status
  - api_docs:
      layout: even-vertical
      root: .
      panes:
        - task docs:server:open
        - task docs:missed
